/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental;

import static java.lang.Math.toIntExact;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author cordo
 */
public class cruddata extends javax.swing.JFrame {

    /**
     * Creates new form cruddata
     */
    public cruddata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        suk = new com.toedter.calendar.JDateChooser();
        luar = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        no_struk = new javax.swing.JTextField();
        no_pol = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        lama = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        print.setText("Print");
        getContentPane().add(print);
        print.setBounds(400, 160, 55, 23);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(330, 80, 73, 23);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(340, 40, 57, 23);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(360, 110, 63, 23);
        getContentPane().add(name);
        name.setBounds(50, 70, 140, 30);
        getContentPane().add(suk);
        suk.setBounds(70, 230, 91, 20);
        getContentPane().add(luar);
        luar.setBounds(70, 270, 91, 20);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 34, 14);
        getContentPane().add(alamat);
        alamat.setBounds(50, 110, 140, 30);
        getContentPane().add(no_struk);
        no_struk.setBounds(50, 150, 140, 30);
        getContentPane().add(no_pol);
        no_pol.setBounds(50, 190, 140, 30);
        getContentPane().add(harga);
        harga.setBounds(50, 360, 140, 30);
        getContentPane().add(lama);
        lama.setBounds(50, 320, 140, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(80, 290, 63, 23);

        setBounds(0, 0, 659, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String masuk = dateFormat.format(suk.getDate());
        String keluar = dateFormat.format(luar.getDate());
        if(     name.getText().equals("")||
                alamat.getText().equals("")||
                no_struk.getText().equals("")||
                no_pol.getText().equals("")||
                suk.getDate().equals("")||
                luar.getDate().equals("")||
                lama.getText().equals("")||
                harga.getText().equals("")
                
                ){
            JOptionPane.showMessageDialog(this,"Hara Data Diperiksa","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO `datapinjam`(`nama`, `alamat`, `noresi`, `nopol`, `pinjam`, `kembali`, `harga`)"
                    + "VALUES('"
                    +name.getText()+"','"
                    +alamat.getText()+"','"
                    +no_struk.getText()+"','"
                    +no_pol.getText()+"','"
                    +masuk+"','"
                    +keluar+"','"
                    +harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this,"Data Berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);            
            }else{
                JOptionPane.showMessageDialog(this,"Data Gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        alamat.setText("");
        no_struk.setText("");
        no_pol.setText("");
        lama.setText("");
        harga.setText("");
        suk.setCalendar(null);
        luar.setCalendar(null);
        
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Date masuk = suk.getDate();
        Date keluar = luar.getDate();
        long startT = masuk.getTime();
        long endT = keluar.getTime();
        long selisih = endT - startT;
        long durasi = selisih / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();
        
        lama.setText(" "+selisih+" Hari");
        
        int lama = toIntExact(selisih);
        int total= lama * 20000;
        String Harga=Integer.toString(total);
        harga.setText(Harga);
        
    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cruddata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lama;
    private com.toedter.calendar.JDateChooser luar;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no_pol;
    private javax.swing.JTextField no_struk;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser suk;
    // End of variables declaration//GEN-END:variables

    public void SelectedData() {
        
    }
}
