/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental;

import static com.itextpdf.text.pdf.PdfName.TA;
import java.awt.print.PrinterException;
import static java.lang.Math.toIntExact;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cordo
 */
public class ruddata extends javax.swing.JFrame {

    /**
     * Creates new form cruddata
     */
    public ruddata() {
        initComponents();
        SetTanggal();
    }
    private void SetTanggal() 
    { 
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText(kal.format(skrg));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        suk = new com.toedter.calendar.JDateChooser();
        luar = new com.toedter.calendar.JDateChooser();
        alamat = new javax.swing.JTextField();
        no_struk = new javax.swing.JTextField();
        no_pol = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        lama = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        labeltanggal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cetak.setBackground(new java.awt.Color(255, 255, 153));
        cetak.setText("Print");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak);
        cetak.setBounds(370, 200, 80, 40);

        save.setBackground(new java.awt.Color(153, 255, 153));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(370, 160, 80, 40);

        clear.setBackground(new java.awt.Color(255, 153, 153));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(370, 120, 80, 40);
        getContentPane().add(name);
        name.setBounds(150, 120, 220, 40);
        getContentPane().add(suk);
        suk.setBounds(150, 280, 220, 40);
        getContentPane().add(luar);
        luar.setBounds(150, 320, 220, 40);
        getContentPane().add(alamat);
        alamat.setBounds(150, 160, 220, 40);
        getContentPane().add(no_struk);
        no_struk.setBounds(150, 200, 220, 40);
        getContentPane().add(no_pol);
        no_pol.setBounds(150, 240, 220, 40);
        getContentPane().add(harga);
        harga.setBounds(150, 440, 220, 40);

        lama.setEditable(false);
        getContentPane().add(lama);
        lama.setBounds(150, 400, 220, 40);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(150, 360, 220, 40);

        labeltanggal.setText("TanggalNow");
        getContentPane().add(labeltanggal);
        labeltanggal.setBounds(820, 20, 80, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "No Struk", "No Pol", "Peminjaman", "Pengembalian", "Harga"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(450, 120, 560, 330);

        refresh.setBackground(new java.awt.Color(153, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(370, 240, 80, 40);

        delet.setBackground(new java.awt.Color(255, 153, 255));
        delet.setText("Delete");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });
        getContentPane().add(delet);
        delet.setBounds(370, 280, 80, 40);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 320, 80, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 70, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 70, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("No.Struk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 200, 70, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("No.Pol");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 240, 70, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Pinjam");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 280, 70, 40);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Kembali");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 320, 70, 40);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Durasi");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 400, 70, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Harga");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 440, 70, 40);

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel1.setText("VIXMI RENT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 20, 114, 30);

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jLabel10.setText("JL.KEBONSARI 5 NO.7J JAMBANGAN,SURABAYA ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 50, 250, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 120);

        jPanel2.setBackground(new java.awt.Color(236, 239, 241));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 120, 420, 40);

        jPanel3.setBackground(new java.awt.Color(207, 216, 220));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 160, 340, 40);

        jPanel4.setBackground(new java.awt.Color(176, 190, 197));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 200, 340, 40);

        jPanel5.setBackground(new java.awt.Color(144, 164, 174));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(30, 240, 340, 40);

        jPanel6.setBackground(new java.awt.Color(120, 144, 156));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(30, 280, 340, 40);

        jPanel7.setBackground(new java.awt.Color(84, 110, 122));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(30, 360, 420, 40);

        jPanel8.setBackground(new java.awt.Color(96, 125, 139));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(30, 320, 340, 40);

        jPanel9.setBackground(new java.awt.Color(69, 90, 100));
        getContentPane().add(jPanel9);
        jPanel9.setBounds(30, 400, 420, 40);

        jPanel10.setBackground(new java.awt.Color(55, 71, 79));
        getContentPane().add(jPanel10);
        jPanel10.setBounds(30, 440, 980, 40);

        setBounds(0, 0, 1059, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String masuk = dateFormat.format(suk.getDate());
        String keluar = dateFormat.format(luar.getDate());
        if(     name.getText().equals("")||
                alamat.getText().equals("")||
                no_struk.getText().equals("")||
                no_pol.getText().equals("")||
                suk.getDate().equals("")||
                luar.getDate().equals("")||
                lama.getText().equals("")||
                harga.getText().equals("")
                
                ){
            JOptionPane.showMessageDialog(this,"Hara Data Diperiksa","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO `datapinjam`(`nama`, `alamat`, `noresi`, `nopol`, `pinjam`, `kembali`, `harga`)"
                    + "VALUES('"
                    +name.getText()+"','"
                    +alamat.getText()+"','"
                    +no_struk.getText()+"','"
                    +no_pol.getText()+"','"
                    +masuk+"','"
                    +keluar+"','"
                    +harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this,"Data Berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                SelectedData();
            }else{
                JOptionPane.showMessageDialog(this,"Data Gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        alamat.setText("");
        no_struk.setText("");
        no_pol.setText("");
        lama.setText("");
        harga.setText("");
        suk.setCalendar(null);
        luar.setCalendar(null);
        
    }//GEN-LAST:event_clearActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Date pinjam = suk.getDate();
        Date kembali = luar.getDate();
        long startTime = pinjam.getTime();
        long endTime = kembali.getTime();
        long bedaWaktu = endTime - startTime;
        long bedaHari = bedaWaktu / (1000 * 60 * 60 * 24);
        DateFormat dateFormat = DateFormat.getDateInstance();
        
        lama.setText(" "+bedaHari+" hari");
        
        int Lama = toIntExact(bedaHari);
        int total = Lama * 20000;
        String Harga = Integer.toString(total);
        
        harga.setText(Harga);
        
        String nam = name.getText();
        String alam = alamat.getText();
        String struk = no_struk.getText();
        String plat = no_pol.getText();
        String masuk = dateFormat.format(suk.getDate());
        String keluar = dateFormat.format(luar.getDate());
        String dura = lama.getText();
        String harg = harga.getText();
        String tang = labeltanggal.getText();
        
        TA.append("		RENTAL MOTOR VIXMI\n"+
"                         JL.KEBONSARI 5 NO.7J JAMBANGAN,SURABAYA\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
" No Nota: "+struk+"                                                                           Tanggal: "+tang+"\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
"\n"+
"\n"+
"\n"+
"\n"+
" Nama Peminjam 	: "+nam+"\n"+
"\n"+
" Alamat 		: "+alam+"\n"+
"\n"+
" Nomor Polisi 		: "+plat+"\n"+
"\n"+
" Tanggal Pinjaman 	: "+masuk+"\n"+
"\n"+
" Tanggal Pengembalian	: "+keluar+"\n"+
"\n"+
" Durasi Peminjaman	: "+dura+"\n"+
"\n"+
"\n"+
" Harga Sewa		: Rp."+harg+"\n"+
"\n"+
"\n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
"    MOTOR HARAP DIKEMBALIKAN PADA WAKTUNYA.APABILA MELEBIHI\n"+
"    JATUH TEMPO,MAKA AKAN DIKENAKAN DENDA Rp.30000 PERHARI.\n"+
"    SEBELUM MENYEWA HARAP DIPERIKSA KONDISI MOTOR DAHULU \n"+
"    KARENA APABILA SAAT DIKEMBALIKAN DITEMUKAN KERUSAKAN \n"+
"    MAKA PENYEWA DIKENAKAN GANTI RUGI SESUAI KERUSAKAN NYA \n"+
"--------------------------------------------------------------------------------------------------------------------- \n"+
"                                                          ~TERIMAKASIH~");
        
    }//GEN-LAST:event_hitungActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        try{
            boolean complete = TA.print();
            if(complete){
                JOptionPane.showMessageDialog(null,"Done Printing","Information",JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(null,"Printing","Printer",JOptionPane.ERROR_MESSAGE);
            }
        }catch(PrinterException a){
            JOptionPane.showMessageDialog(null,cetak);
        }
            
    }//GEN-LAST:event_cetakActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != 1) {
            name.setText(tblData.getValueAt(baris, 0).toString());
            alamat.setText(tblData.getValueAt(baris, 1).toString());
            no_struk.setText(tblData.getValueAt(baris, 2).toString());
            no_pol.setText(tblData.getValueAt(baris, 3).toString());

            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tblData.getValueAt(baris, 4).toString());
                dateFormat = date.parse(tblData.getValueAt(baris, 5).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(ruddata.class.getName()).log(Level.SEVERE, null, ex);
            }

            suk.setDate(dateFormat);
            suk.setDate(dateFormat);
            harga.setText(tblData.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        SelectedData();
    }//GEN-LAST:event_refreshActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1) 
        {
            String Nama = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM datapinjam WHERE Nama='"+Nama+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) 
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                SelectedData();
                
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deletActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ruddata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruddata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton cetak;
    private javax.swing.JButton clear;
    private javax.swing.JButton delet;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField lama;
    private com.toedter.calendar.JDateChooser luar;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no_pol;
    private javax.swing.JTextField no_struk;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser suk;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    public void SelectedData() {
        String kolom[] = {"Nama","Alamat","NoStruk","NoPol","TanggalPinjam","TangalKembali","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM datapinjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String Nama = rs.getString(1);
                String Alamat = rs.getString(2);
                String NoStruk = rs.getString(3);
                String NoPol = rs.getString(4);
                String TanggalPinjam = rs.getString(5);
                String TanggalKembali = rs.getString(6);
                String Harga = rs.getString(7);
                String data[] = {Nama,Alamat,NoStruk,NoPol,TanggalPinjam,TanggalKembali,Harga};
                dtm.addRow(data);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(ruddata.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
